// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package port

import (
	"github.com/o-ga09/GO_TEMPLATE_RESTAPI/api/domain"
	"sync"
)

// Ensure, that InputPortMock does implement InputPort.
// If this is not the case, regenerate this file with moq.
var _ InputPort = &InputPortMock{}

// InputPortMock is a mock implementation of InputPort.
//
//	func TestSomethingThatUsesInputPort(t *testing.T) {
//
//		// make and configure a mocked InputPort
//		mockedInputPort := &InputPortMock{
//			CreateFunc: func(createJson domain.CreateJson) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(id domain.UserID) error {
//				panic("mock out the Delete method")
//			},
//			GetAllFunc: func() (domain.Entities, error) {
//				panic("mock out the GetAll method")
//			},
//			GetByIdFunc: func(id domain.UserID) (domain.Entity, error) {
//				panic("mock out the GetById method")
//			},
//			UpdateFunc: func(id domain.UserID, param domain.CreateJson) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedInputPort in code that requires InputPort
//		// and then make assertions.
//
//	}
type InputPortMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(createJson domain.CreateJson) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id domain.UserID) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() (domain.Entities, error)

	// GetByIdFunc mocks the GetById method.
	GetByIdFunc func(id domain.UserID) (domain.Entity, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id domain.UserID, param domain.CreateJson) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// CreateJson is the createJson argument value.
			CreateJson domain.CreateJson
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID domain.UserID
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// GetById holds details about calls to the GetById method.
		GetById []struct {
			// ID is the id argument value.
			ID domain.UserID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID domain.UserID
			// Param is the param argument value.
			Param domain.CreateJson
		}
	}
	lockCreate  sync.RWMutex
	lockDelete  sync.RWMutex
	lockGetAll  sync.RWMutex
	lockGetById sync.RWMutex
	lockUpdate  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *InputPortMock) Create(createJson domain.CreateJson) error {
	if mock.CreateFunc == nil {
		panic("InputPortMock.CreateFunc: method is nil but InputPort.Create was just called")
	}
	callInfo := struct {
		CreateJson domain.CreateJson
	}{
		CreateJson: createJson,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(createJson)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedInputPort.CreateCalls())
func (mock *InputPortMock) CreateCalls() []struct {
	CreateJson domain.CreateJson
} {
	var calls []struct {
		CreateJson domain.CreateJson
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *InputPortMock) Delete(id domain.UserID) error {
	if mock.DeleteFunc == nil {
		panic("InputPortMock.DeleteFunc: method is nil but InputPort.Delete was just called")
	}
	callInfo := struct {
		ID domain.UserID
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedInputPort.DeleteCalls())
func (mock *InputPortMock) DeleteCalls() []struct {
	ID domain.UserID
} {
	var calls []struct {
		ID domain.UserID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *InputPortMock) GetAll() (domain.Entities, error) {
	if mock.GetAllFunc == nil {
		panic("InputPortMock.GetAllFunc: method is nil but InputPort.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedInputPort.GetAllCalls())
func (mock *InputPortMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetById calls GetByIdFunc.
func (mock *InputPortMock) GetById(id domain.UserID) (domain.Entity, error) {
	if mock.GetByIdFunc == nil {
		panic("InputPortMock.GetByIdFunc: method is nil but InputPort.GetById was just called")
	}
	callInfo := struct {
		ID domain.UserID
	}{
		ID: id,
	}
	mock.lockGetById.Lock()
	mock.calls.GetById = append(mock.calls.GetById, callInfo)
	mock.lockGetById.Unlock()
	return mock.GetByIdFunc(id)
}

// GetByIdCalls gets all the calls that were made to GetById.
// Check the length with:
//
//	len(mockedInputPort.GetByIdCalls())
func (mock *InputPortMock) GetByIdCalls() []struct {
	ID domain.UserID
} {
	var calls []struct {
		ID domain.UserID
	}
	mock.lockGetById.RLock()
	calls = mock.calls.GetById
	mock.lockGetById.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *InputPortMock) Update(id domain.UserID, param domain.CreateJson) error {
	if mock.UpdateFunc == nil {
		panic("InputPortMock.UpdateFunc: method is nil but InputPort.Update was just called")
	}
	callInfo := struct {
		ID    domain.UserID
		Param domain.CreateJson
	}{
		ID:    id,
		Param: param,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, param)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedInputPort.UpdateCalls())
func (mock *InputPortMock) UpdateCalls() []struct {
	ID    domain.UserID
	Param domain.CreateJson
} {
	var calls []struct {
		ID    domain.UserID
		Param domain.CreateJson
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
