version: "3.9"
services:
  api-dbsrv-01:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: api-dbsrv-01
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: api
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: api
      MYSQL_TCP_PORT: 3306
    volumes:
      - api-dbsrv01-data:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - replica-network
  api-dbsrv-02:
    image: redis:6.0-alpine3.18
    container_name: api-dbsrv-02
    ports:
      - 6379:6379
    networks:
      - replica-network
  api-srv:
    image: api-srv
    depends_on:
      - api-dbsrv-01
      - api-dbsrv-02
    build:
      context: .
      dockerfile: go/dockerfile
      args:
        - target=dev
    environment:
      ENV: dev
      PORT: 8000
      DB_URL: api:P@ssw0rd@tcp(api-dbsrv-01)/api?charset=utf8&parseTime=True&loc=Local
      REDIS_URL: "api-dbsrv-02:6379"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    networks:
      - replica-network
volumes:
  api-dbsrv01-data:
networks:
  replica-network:
    driver: bridge
