// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"context"
	"sync"
)

// Ensure, that IUserDomainServiceMock does implement IUserDomainService.
// If this is not the case, regenerate this file with moq.
var _ IUserDomainService = &IUserDomainServiceMock{}

// IUserDomainServiceMock is a mock implementation of IUserDomainService.
//
//	func TestSomethingThatUsesIUserDomainService(t *testing.T) {
//
//		// make and configure a mocked IUserDomainService
//		mockedIUserDomainService := &IUserDomainServiceMock{
//			DeleteUserFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteUser method")
//			},
//			EditUserFunc: func(ctx context.Context, param *User) error {
//				panic("mock out the EditUser method")
//			},
//			FindUserFunc: func(ctx context.Context) ([]*User, int64, error) {
//				panic("mock out the FindUser method")
//			},
//			FindUserByIdFunc: func(ctx context.Context, id string) (*User, error) {
//				panic("mock out the FindUserById method")
//			},
//		}
//
//		// use mockedIUserDomainService in code that requires IUserDomainService
//		// and then make assertions.
//
//	}
type IUserDomainServiceMock struct {
	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, id string) error

	// EditUserFunc mocks the EditUser method.
	EditUserFunc func(ctx context.Context, param *User) error

	// FindUserFunc mocks the FindUser method.
	FindUserFunc func(ctx context.Context) ([]*User, int64, error)

	// FindUserByIdFunc mocks the FindUserById method.
	FindUserByIdFunc func(ctx context.Context, id string) (*User, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// EditUser holds details about calls to the EditUser method.
		EditUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Param is the param argument value.
			Param *User
		}
		// FindUser holds details about calls to the FindUser method.
		FindUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// FindUserById holds details about calls to the FindUserById method.
		FindUserById []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
	}
	lockDeleteUser   sync.RWMutex
	lockEditUser     sync.RWMutex
	lockFindUser     sync.RWMutex
	lockFindUserById sync.RWMutex
}

// DeleteUser calls DeleteUserFunc.
func (mock *IUserDomainServiceMock) DeleteUser(ctx context.Context, id string) error {
	if mock.DeleteUserFunc == nil {
		panic("IUserDomainServiceMock.DeleteUserFunc: method is nil but IUserDomainService.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, id)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedIUserDomainService.DeleteUserCalls())
func (mock *IUserDomainServiceMock) DeleteUserCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// EditUser calls EditUserFunc.
func (mock *IUserDomainServiceMock) EditUser(ctx context.Context, param *User) error {
	if mock.EditUserFunc == nil {
		panic("IUserDomainServiceMock.EditUserFunc: method is nil but IUserDomainService.EditUser was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Param *User
	}{
		Ctx:   ctx,
		Param: param,
	}
	mock.lockEditUser.Lock()
	mock.calls.EditUser = append(mock.calls.EditUser, callInfo)
	mock.lockEditUser.Unlock()
	return mock.EditUserFunc(ctx, param)
}

// EditUserCalls gets all the calls that were made to EditUser.
// Check the length with:
//
//	len(mockedIUserDomainService.EditUserCalls())
func (mock *IUserDomainServiceMock) EditUserCalls() []struct {
	Ctx   context.Context
	Param *User
} {
	var calls []struct {
		Ctx   context.Context
		Param *User
	}
	mock.lockEditUser.RLock()
	calls = mock.calls.EditUser
	mock.lockEditUser.RUnlock()
	return calls
}

// FindUser calls FindUserFunc.
func (mock *IUserDomainServiceMock) FindUser(ctx context.Context) ([]*User, int64, error) {
	if mock.FindUserFunc == nil {
		panic("IUserDomainServiceMock.FindUserFunc: method is nil but IUserDomainService.FindUser was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockFindUser.Lock()
	mock.calls.FindUser = append(mock.calls.FindUser, callInfo)
	mock.lockFindUser.Unlock()
	return mock.FindUserFunc(ctx)
}

// FindUserCalls gets all the calls that were made to FindUser.
// Check the length with:
//
//	len(mockedIUserDomainService.FindUserCalls())
func (mock *IUserDomainServiceMock) FindUserCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockFindUser.RLock()
	calls = mock.calls.FindUser
	mock.lockFindUser.RUnlock()
	return calls
}

// FindUserById calls FindUserByIdFunc.
func (mock *IUserDomainServiceMock) FindUserById(ctx context.Context, id string) (*User, error) {
	if mock.FindUserByIdFunc == nil {
		panic("IUserDomainServiceMock.FindUserByIdFunc: method is nil but IUserDomainService.FindUserById was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindUserById.Lock()
	mock.calls.FindUserById = append(mock.calls.FindUserById, callInfo)
	mock.lockFindUserById.Unlock()
	return mock.FindUserByIdFunc(ctx, id)
}

// FindUserByIdCalls gets all the calls that were made to FindUserById.
// Check the length with:
//
//	len(mockedIUserDomainService.FindUserByIdCalls())
func (mock *IUserDomainServiceMock) FindUserByIdCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockFindUserById.RLock()
	calls = mock.calls.FindUserById
	mock.lockFindUserById.RUnlock()
	return calls
}
